### ISSUE TITLE
Unable to upload timetable

### ISSUE THREAD

**Issue by huixiang01** [OpenSUTD/sutd-timetable#14]
![image](https://user-images.githubusercontent.com/45475865/72790075-d3c28b00-3c6f-11ea-9e6a-352e51e70dd3.png)

![image](https://user-images.githubusercontent.com/45475865/72790449-93afd800-3c70-11ea-9366-c9b06e65cf3d.png)

I right-clicked and choose my html to upload. And this is what I have

**Comment by tlkh** [comment]
Strange, I am able to upload without issue...

I did however run into good old friend #12, manually changing the semester in the url to `2020-0` works.

<img width="1505" alt="Screenshot 2020-01-21 at 7 22 10 PM" src="https://user-images.githubusercontent.com/5409617/72800960-720c1c00-3c83-11ea-803c-f18d66b35db1.png">

**Comment by flamanta** [comment]
I was able to upload the timetable without issue, and the timetable file was retrieved from [here](https://sams.sutd.edu.sg/psc/CSPRD/EMPLOYEE/HRMS/c/SA_LEARNER_SERVICES.SSR_SSENRL_LIST.GBL) (make sure you log into the [SAMS portal](https://sams.sutd.edu.sg/) first). 

Can confirm the calendar subscription URL has to be changed from `2019-2` to `2020-0` to work properly.

**Comment by huixiang01** [comment]
> Strange, I am able to upload without issue...
> 
> I did however run into good old friend #12, manually changing the semester in the url to `2020-0` works.
> 
> <img alt="Screenshot 2020-01-21 at 7 22 10 PM" width="1505" src="https://user-images.githubusercontent.com/5409617/72800960-720c1c00-3c83-11ea-803c-f18d66b35db1.png">

downloading is not a problem... for now. Uploading is a problem. I still have the same error

**Comment by huixiang01** [comment]
> e
Yup I did that jn. Still the same error.

**Comment by huixiang01** [comment]
> I was able to upload the timetable without issue, and the timetable file was retrieved from [here](https://sams.sutd.edu.sg/psc/CSPRD/EMPLOYEE/HRMS/c/SA_LEARNER_SERVICES.SSR_SSENRL_LIST.GBL) (make sure you log into the [SAMS portal](https://sams.sutd.edu.sg/) first).
> 
> Can confirm the calendar subscription URL has to be changed from `2019-2` to `2020-0` to work properly.

Yup i did that just now. Still the same error

**Comment by tlkh** [comment]
@huixiang01 what's the file extension of the file you are uploading? It should say GBL or something.

**Comment by huixiang01** [comment]
> @huixiang01 what's the file extension of the file you are uploading? It should say GBL or something.

weird i obtained html. What exactly I should right-click on?

**Comment by huixiang01** [comment]
Miracle-ly, I don't know what happened. But it works now. Thanks for the help!
