### ISSUE TITLE
New HASS module not appearing

### ISSUE THREAD

**Issue by causztic** [OpenSUTD/sutd-timetable#5]
[SA_LEARNER_SERVICES.SSR_SSENRL_LIST.GBL.txt](https://github.com/OpenSUTD/sutd-timetable/files/3171953/SA_LEARNER_SERVICES.SSR_SSENRL_LIST.GBL.txt)

My timetable is attached.

![Screenshot 2019-05-13 at 4 46 58 PM](https://user-images.githubusercontent.com/2081441/57608126-01aee600-759f-11e9-9855-7330e7fd8e40.png)

On uploading the file it shows the modules i'm currently taking, but afterwards when I'm trying to find it in the subjects list it is missing.

![Screenshot 2019-05-13 at 4 47 25 PM](https://user-images.githubusercontent.com/2081441/57608178-1ab79700-759f-11e9-97d8-39fa4a375e07.png)

Module code is 02.128.

If I were to try fixing this where should I look at first?

**Comment by Yustynn** [comment]
Hey @causztic I've got a fix already, no worries. There are actually a couple more issues (no new mods show up, when mods do show up the time is wrong).

Will push and merge by Sunday, hopefully.

**Comment by Yustynn** [comment]
Resolved already, although there's another problem where PM times aren't being parsed correctly. I think the `date-fns` library itself is at fault, will push a fix soon.
